#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 EoS Project
#
# tools/embed_stage1_hash.py
#
# Reads a Stage-1 binary, computes its SHA-256 digest, and generates the C
# source file that defines the constants stage0/jump_stage1.c verifies against.
#
# Usage:
#   python embed_stage1_hash.py --input eboot_firmware.bin --output stage1_hash.c

"""Generate the C definitions of the Stage-1 hash and size.

The size is checked before anything is hashed. This script used to take
``os.path.getsize()`` verbatim: when the stage-1 link produced an empty image
(no ENTRY and no kept vector section, so --gc-sections discarded everything)
it emitted ``stage1_expected_size = 0u`` and the SHA-256 of the empty string,
printed both as a normal build line, and stage-0 then "verified" stage-1 by
hashing zero bytes and jumping. A verification step that cannot run must
fail, not pass; that starts with the build refusing to describe an image that
is not there.
"""

import argparse
import hashlib
import os
import sys
from pathlib import Path

# A stage-1 that verifies an Ed25519 signature cannot be smaller than the
# verifier; the stm32f4 image is ~13 KiB at -Os. The floor sits well below
# that and well above what a link with nothing but a vector table produces
# (64 bytes), so it separates "built" from "empty or gutted", not "small".
DEFAULT_MIN_SIZE = 4096


def compute_sha256(filepath: Path) -> bytes:
    """Return the SHA-256 digest of *filepath*."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        while True:
            chunk = f.read(65536)
            if not chunk:
                break
            h.update(chunk)
    return h.digest()


def format_c_array(digest: bytes) -> str:
    """Format a 32-byte digest as a C initializer list."""
    lines = []
    for i in range(0, len(digest), 8):
        values = ", ".join(f"0x{b:02x}" for b in digest[i : i + 8])
        lines.append(f"    {values},")
    return "\n".join(lines)


def generate_source(digest: bytes, size: int, input_name: str) -> str:
    """Return the full C source file content.

    These definitions must have external linkage and must match the extern
    declarations in stage0/jump_stage1.c exactly. An earlier version emitted a
    header with a `static` array and no size at all, which could not satisfy
    those externs -- ebldr_stage0 failed to link with "undefined reference to
    stage1_expected_hash".
    """
    hex_str = digest.hex()
    array_body = format_c_array(digest)

    return f"""\
// SPDX-License-Identifier: MIT
// Copyright (c) 2026 EoS Project
//
// AUTO-GENERATED by tools/embed_stage1_hash.py — do not edit.
// Source binary: {input_name}
// SHA-256:       {hex_str}
// Size:          {size} bytes

#include <stdint.h>

const uint8_t stage1_expected_hash[32] = {{
{array_body}
}};

const uint32_t stage1_expected_size = {size}u;
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit the C definitions of the Stage-1 hash and size."
    )
    parser.add_argument(
        "--input", required=True,
        help="Path to the Stage-1 binary (e.g. eboot_firmware.bin)"
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output C source path (e.g. stage1_hash.c)",
    )
    parser.add_argument(
        "--min-size",
        type=int,
        default=DEFAULT_MIN_SIZE,
        help=f"Smallest stage-1 image accepted, in bytes (default {DEFAULT_MIN_SIZE}); "
             f"an empty image is refused whatever this is set to",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.is_file():
        print(f"Error: input file not found: {input_path}", file=sys.stderr)
        return 1

    size = os.path.getsize(input_path)
    if size == 0:
        print(f"Error: {input_path} is empty: there is no stage-1 image to verify. "
              f"The stage-1 link produced nothing -- check that the board's stage-1 "
              f"linker script has ENTRY() and keeps the vector section.", file=sys.stderr)
        return 1
    if size < args.min_size:
        print(f"Error: {input_path} is {size} bytes, below the {args.min_size}-byte floor "
              f"for a stage-1 image; a link that small did not produce the stage it "
              f"claims to (pass --min-size to change the floor).", file=sys.stderr)
        return 1
    digest = compute_sha256(input_path)
    source = generate_source(digest, size, input_path.name)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(source, encoding="utf-8")

    print(f"Generated {output_path}")
    print(f"  SHA-256: {digest.hex()}")
    print(f"  Source:  {input_path} ({size} bytes)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
