// SPDX-License-Identifier: MIT
// Copyright (c) 2026 EoS Project

/**
 * @file test_keystore_production.c
 * @brief core/keystore.c compiled with EBLDR_PRODUCTION_KEY.
 *
 * The production branch of the keystore -- the one a release artifact is
 * built from -- had never been compiled: it declared an extern that nothing
 * defined, so following the #warning's own instruction produced a link
 * error. This suite builds core/keystore.c the way a Release board build
 * does (EBLDR_PRODUCTION_KEY defined, ebldr_production_key[] generated by
 * cmake/ProductionKey.cmake from a fixture key) and asks the no-OTP path for
 * its anchor. The suite's own keystore.o defines every keystore symbol, so
 * the copy inside eboot_core is never pulled in: the object under test is
 * the one compiled here, not the development-key one.
 *
 * The fixture key is RFC 8032 section 7.1 TEST 2's public key: a real curve
 * point that is not the development key, so the assertions can tell the two
 * apart.
 */

#include "eos_keystore.h"
#include "eos_production_key.h"
#include "eos_hal.h"
#include "../vectors/fw_update_test_sigs.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* RFC 8032 section 7.1, TEST 2, PUBLIC KEY: what tests/CMakeLists.txt hands
 * to ebldr_write_production_key_source() for this suite. */
static const uint8_t k_fixture_key[EOS_ED25519_PUB_KEY_SIZE] = {
    0x3d,0x40,0x17,0xc3,0xe8,0x43,0x89,0x5a,0x92,0xb7,0x0a,0xa7,0x4d,0x1b,0x7e,0xbc,
    0x9c,0x98,0x2c,0xcf,0x2e,0xc4,0x96,0x8c,0xc0,0xcd,0x55,0xf1,0x2a,0xf4,0x66,0x0c,
};

/* A board with no OTP at all: eos_hal_otp_read() reports EOS_ERR_NOT_SUPPORTED
 * and the keystore takes the compiled-in path. */
static const eos_board_ops_t no_otp_board = { 0 };

static int tests_run = 0;
static int tests_passed = 0;

#define TEST(name) \
    static void name(void); \
    static void run_##name(void) { \
        printf("  %-62s ", #name); \
        tests_run++; \
        name(); \
        tests_passed++; \
        printf("[PASS]\n"); \
    } \
    static void name(void)

#define ASSERT(cond) do { \
    if (!(cond)) { \
        printf("[FAIL] %s:%d: %s\n", __FILE__, __LINE__, #cond); \
        exit(1); \
    } \
} while(0)

/* The generated translation unit defines the symbol keystore.c consumes, and
 * with the bytes the build was configured with. */
TEST(test_generated_symbol_carries_the_configured_key)
{
    ASSERT(memcmp(ebldr_production_key, k_fixture_key, EOS_ED25519_PUB_KEY_SIZE) == 0);
}

/* On a board without OTP the active key is the production key, from the
 * compiled-in source. */
TEST(test_no_otp_board_gets_the_production_key)
{
    eos_keystore_t ks;
    const uint8_t *key = NULL;
    size_t key_len = 0;

    eos_hal_init(&no_otp_board);
    ASSERT(eos_keystore_init(&ks) == EOS_OK);
    ASSERT(ks.source == EOS_KEY_SOURCE_COMPILED);
    ASSERT(eos_keystore_get_active_key(&ks, &key, &key_len) == EOS_OK);
    ASSERT(key_len == EOS_ED25519_PUB_KEY_SIZE);
    ASSERT(memcmp(key, k_fixture_key, EOS_ED25519_PUB_KEY_SIZE) == 0);
}

/* And it is not the development key. eos_test_sig_pubkey is the RFC 8032
 * TEST 1 public key, derived from the RFC's secret by
 * tools/gen_fw_update_test_sigs.py -- the key the #ifndef branch compiles in
 * and the one a release must never carry. */
TEST(test_no_otp_board_does_not_get_the_development_key)
{
    eos_keystore_t ks;
    const uint8_t *key = NULL;
    size_t key_len = 0;

    eos_hal_init(&no_otp_board);
    ASSERT(eos_keystore_init(&ks) == EOS_OK);
    ASSERT(eos_keystore_get_active_key(&ks, &key, &key_len) == EOS_OK);
    ASSERT(memcmp(key, eos_test_sig_pubkey, EOS_ED25519_PUB_KEY_SIZE) != 0);
}

int main(void)
{
    printf("=== eBootloader: Keystore with EBLDR_PRODUCTION_KEY ===\n\n");

    run_test_generated_symbol_carries_the_configured_key();
    run_test_no_otp_board_gets_the_production_key();
    run_test_no_otp_board_does_not_get_the_development_key();

    printf("\n%d/%d tests passed\n", tests_passed, tests_run);
    return (tests_passed == tests_run) ? 0 : 1;
}
